#! /bin/sh
### BEGIN INIT INFO
# Provides:          skeleton
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO

PARTS="vda1 sda1 sdb1 sdc1"

#
# Function that starts the daemon/service
#
do_start()
{

  CURRENT=""
  
  umount /mnt
  for P in $PARTS; do
      if ! test -z "$CURRENT"; then continue; fi
      echo "trying: /dev/$P"
      if mount /dev/$P /mnt/; then
        if test -f /mnt/images; then
           CURRENT=$P
        else
           umount /mnt/
        fi
      fi
  done


  if test -z "$CURRENT"; then echo "error: no disk";exit 1; fi

  # get new image
  ltsp-sync-image &

#  /etc/init.d/ltsp-localuser boot
#  /etc/init.d/ltsp-localnbd start
}

#
# Function that stops the daemon/service
#
do_stop()
{
#  /etc/init.d/ltsp-localuser stop
# /etc/init.d/ltsp-localnbd stop

  # umount sda1
  umount /mnt
}

#
# Function that sends a SIGHUP to the daemon/service
#
do_reload() {
 do_stop
 do_start
}


# main

if ! cat /proc/cmdline | grep -q "loop"; then exit; fi

case "$1" in
  start)
        do_start
	;;
  stop)
        do_stop
	;;
  restart|force-reload|reload)
        do_reload
	;;
  *)
	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
	echo "Usage: $SCRIPTNAME {start|stop|restart|reload}" >&2
	exit 3
	;;
esac

