#! /bin/sh
### BEGIN INIT INFO
# Provides:          skeleton
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO



#
# Function that starts the daemon/service
#
do_start()
{
  # try to mount partition with images
  PARTS="sdc1 sdb1 sda1 vda1"
  CURRENT=""
  umount /mnt
  for P in $PARTS; do
      if ! test -z "$CURRENT"; then continue; fi
      echo -n "trying: /dev/$P ..."
      if mount /dev/$P /mnt/; then
        if test -d /mnt/images; then
           CURRENT=$P
           echo "ok"
        else
           umount /mnt/
           echo "no"
        fi
      fi
  done

  # exit if none found
  if test -z "$CURRENT"; then 
     echo "error: no disk"
     exit 1 
  fi
 
  #prepare local nbd
  BOOT=$(cat /proc/cmdline|cut -d\  -f6|cut -d= -f2)     
  if ! test -d /opt/ltsp/images/; then mkdir -p /opt/ltsp/images/; fi
  if test -f /opt/ltsp/images/i386.img; then 
         rm /opt/ltsp/images/i386.img;
  fi
  chmod a+r /mnt/images/*.img
  ln -s /mnt/${BOOT} /opt/ltsp/images/i386.img
  service nbd-server restart


  # sync new image
  nice ltsp-sync-image &

#  /etc/init.d/ltsp-localuser boot
#   /etc/init.d/ltsp-localnbd start
}

#
# Function that stops the daemon/service
#
do_stop()
{
#  /etc/init.d/ltsp-localuser stop
#   /etc/init.d/ltsp-localnbd stop

   # umount sda1
   umount /mnt
}

#
# Function that sends a SIGHUP to the daemon/service
#
do_reload() {
 do_stop
 do_start
}


# main

if ! cat /proc/cmdline | grep -q "loop"; then exit; fi

case "$1" in
  start)
        do_start
	;;
  stop)
        do_stop
	;;
  restart|force-reload|reload)
        do_reload
	;;
  *)
	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
	echo "Usage: $SCRIPTNAME {start|stop|restart|reload}" >&2
	exit 3
	;;
esac

