#! /bin/sh
### BEGIN INIT INFO
# Provides:          skeleton
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO



#
# Function that starts the daemon/service
#
do_start()
{
  # restore local user setup

  # bind home_local
  mount --bind /mnt/home /home

  if ! test -d /mnt/local/etc/; then mkdir -p /mnt/local/etc; fi
  if test -f /mnt/local/etc/passwd; then 
       cat /rofs/etc/passwd /mnt/local/etc/passwd >/etc/passwd
       cat /rofs/etc/group /mnt/local/etc/group >/etc/group
       cat /rofs/etc/shadow /mnt/local/etc/shadow >/etc/shadow
  fi

}

#
# Function that stops the daemon/service
#
do_stop()
{
  # save local user setup
  echo "" > /mnt/local/etc/passwd
  for user in "$(ls /nmt/home/)"; do
    cat /etc/passwd | grep "^$user" >>/mnt/local/etc/passwd
  done
  echo "" > /mnt/local/etc/shadow
  echo "" > /mnt/local/etc/group
  for name in "$(cat /mnt/local/passwd|cut -d: -f1|xargs)"; do
     cat /etc/shadow|grep "^$name:" >>/mnt/local/etc/shadow
     cat /etc/group|grep "^$name:" >>/mnt/local/etc/group
  done

  # umount /home_local
  umount /home

}

#
# Function that sends a SIGHUP to the daemon/service
#
do_reload() {
 do_stop
 do_start
}

case "$1" in
  start)
        do_start
	;;
  stop)
        do_stop
	;;
  restart|force-reload)
        do_reload
	;;
  *)
	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
	echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
	exit 3
	;;
esac

