#! /bin/sh
### BEGIN INIT INFO
# Provides:          skeleton
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO




# check memory size
MEMTOT=$(cat /proc/meminfo |grep MemTotal|xargs|cut -d\  -f2)
if test $MEMTOT -gt 5000000; then
   LARGE_MEM=true
else
   LARGE_MEM=false
fi

      # update image
#      if cat /proc/cmdline|grep -q "root=/dev/nbd0"; then
#        echo -n "copying i386.img to disk..."
#        cat /dev/nbd0 >/mnt/i386.img
#        echo "ok"
#      fi
      
      
      

   
#else
#    if $LARGE_MEM; then
#      mkdir -p /opt/ltsp/images/
#      ln -s /mnt/images/$(printf "%06i.img" $(cat /mnt/images/version) ) /opt/ltsp/images/i386.img
#     #dd if=/dev/nbd0 of=/opt/ltsp/images/i386.img
#    fi
#fi



#
# Function that starts the daemon/service
#
do_start()
{
   if test -d /mnt/images; then      
      BOOT=$(cat /proc/cmdline|cut -d\  -f6|cut -d= -f2)     
      if ! test -d /opt/ltsp/images/; then mkdir -p /opt/ltsp/images/; fi
      if test -f /opt/ltsp/images/i386.img; then 
         rm /opt/ltsp/images/i386.img;
      fi
      chmod a+r /mnt/images/*.img
      ln -s /mnt/${BOOT} /opt/ltsp/images/i386.img
      service nbd-server restart
   fi
}

#
# Function that stops the daemon/service
#
do_stop()
{
    echo -n ""
}

#
# Function that sends a SIGHUP to the daemon/service
#
do_reload() {
 do_stop
 do_start
}

if ! cat proc/cmdline|grep -q loop; then exit 1; fi

case "$1" in
  update)
        do_update
        ;;
  start)
        do_start
	;;
  stop)
        do_stop
	;;
  restart|force-reload)
        do_reload
	;;
  *)
	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
	echo "Usage: $SCRIPTNAME {start|stop|restart|update}" >&2
	exit 3
	;;
esac

